name: Import AbrezzPjkt to Branch Aberuzz

on:
  workflow_dispatch:

jobs:
  import-job:
    runs-on: self-hosted
    permissions:
      contents: write      # Izin untuk push file biasa
      workflows: write     # Izin KHUSUS untuk push file .github/workflows/

    steps:
      - name: Checkout Repo Kamu
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Konfigurasi Git User
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

      - name: Proses Import Branch
        run: |
          git remote add target_repo https://github.com/Abreuzzs/AbrezzPjkt_Earth.git
          git fetch target_repo Master
          
          # Buat branch lokal baru
          git checkout -b Aberuzz target_repo/Master
          
          # Push ke repo kamu
          git push origin Aberuzz
