name: Build Kernel run-on ubuntu by purdiantoefendi-cyber (Smart Build)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Langkah 1: Checkout Kode Sumber
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          ref: ksun-susfs   # branch kamu
          fetch-depth: 0   # penting agar bisa ambil history penuh
          submodules: recursive  # ini supaya subproject commit (KernelSU-Next) ikut diambil

      # Langkah 2: Setup KernelSU-Next
      - name: Setup KernelSU-Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s v3.1.0-legacy-susfs

      # Langkah 3: Install Dependensi
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc libssl-dev zip curl libstdc++6 git libncurses5-dev bison flex gcc-aarch64-linux-gnu

      # Langkah 4: Unduh Toolchain Clang
      - name: Download Clang Toolchain
        run: git clone https://gitlab.com/PixelOS-Devices/playgroundtc.git --depth=1 clang-toolchain

      # Langkah 5: Atur Environment Build & Path
      - name: Set Up Build Environment
        run: |
          # Ekspor toolchain ke PATH GitHub Actions
          echo "${{ github.workspace }}/clang-toolchain/bin" >> $GITHUB_PATH

      # Langkah 6: Generate .config
      - name: Generate .config
        run: |
          ARGS="ARCH=arm64 SUBARCH=arm64 KBUILD_BUILD_USER=DianTk_Modz_sukiSU KBUILD_BUILD_HOST=GitHub-Actions CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-"
          make O=out $ARGS earth_defconfig

      # Langkah 7: Kompilasi Kernel
      - name: Compile Kernel
        run: |
          ARGS="ARCH=arm64 SUBARCH=arm64 KBUILD_BUILD_USER=DianTk_Modz_sukiSU KBUILD_BUILD_HOST=GitHub-Actions CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-"
          make O=out -j$(nproc) KCFLAGS="-Wno-error" LLVM=1 $ARGS || make O=out -j1 KCFLAGS="-Wno-error" LLVM=1 $ARGS

      # Langkah 8: Upload
      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: |
            out/arch/arm64/boot/Image.gz*
            out/arch/arm64/boot/dts/**/*.dtb
